COORDINATE_REQUEST_PARAMS:
                          - latitude
                          - longitude

ADDRESS_REQUEST_PARAMS:
                          - address

REDIS_URL:            redis://localhost:6379/0

CELERY_BROKER_URL:    amqp://admin:admin@localhost:5672


HOST:                 0.0.0.0

PORT:                 1989