COORDINATE_REQUEST_PARAMS:
                      - latitude
                      - longitude

ADDRESS_REQUEST_PARAMS:
                      - address

REDIS_URL:            redis://redis:6379/0

CELERY_BROKER_URL:    amqp://admin:admin@rabbit//


HOST:                 0.0.0.0

PORT:                 1989

