version: '3'

services:

  redis:
    image: redis:latest
    hostname: redis
    ports:
      #- 6379:6379
      - "6379:6379"

  rabbit:
    hostname: rabbit
    image: rabbitmq:management
    command: rabbitmq-server
    environment:
      RABBITMQ_DEFAULT_USER: "admin"
      RABBITMQ_DEFAULT_PASS: "admin"
    ports:
      - 5672:5672
      - 15672:15672

  webservice:
    build:
      context: .
      dockerfile: Dockerfile
    hostname: webservice
    command: ./shell_scripts/run_webservice.sh
    volumes:
      - .:/app
    ports:
      - 1989:1989
    links:
      - rabbit
      - redis

  worker:
    restart: on-failure
    build:
      context: .
      dockerfile: Dockerfile
    command: ./shell_scripts/run_celery.sh
    volumes:
      - .:/app
    links:
      - rabbit
      - redis
    depends_on:
      - rabbit
