version: '3'

services:

  redis:
    image: redis:latest
    hostname: redis

  rabbit:
    hostname: rabbit
    image: rabbitmq:latest
    environment:
      RABBITMQ_DEFAULT_USER: "admin"
      RABBITMQ_DEFAULT_PASS: "admin"

  webservice:
    build:
      context: .
      dockerfile: Dockerfile
    hostname: webservice
    command: ./shell_scripts/run_webservice.sh
    volumes:
      - .:/app
    ports:
      - "1989:1989"
    links:
      - rabbit
      - redis

  worker:
    build:
      context: .
      dockerfile: Dockerfile
    command: ./shell_scripts/run_celery.sh
    volumes:
      - .:/app
    links:
      - rabbit
      - redis
    depends_on:
      - rabbit